name: Publish to TestPyPI

on:
  push:
    tags:
      - 'test/v*'
  workflow_dispatch: {}

jobs:
  build-and-publish-testpypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build

      - name: Verify tag matches version
        run: |
          # Expect tags like test/v0.1.2
          RAW_REF="$GITHUB_REF_NAME"
          TAG_NAME="${RAW_REF#test/v}"
          echo "Ref: $RAW_REF | Parsed tag: $TAG_NAME"
          PY_VER=$(python -c 'import tomllib; print(tomllib.load(open("pyproject.toml","rb"))["project"]["version"])')
          echo "pyproject version: $PY_VER"
          if [ "$TAG_NAME" != "$PY_VER" ]; then
            echo "Error: tag (test/v$TAG_NAME) does not match pyproject version ($PY_VER)"
            exit 1
          fi

      - name: Build package
        run: python -m build

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
